name: CI

on:
  push:
    branches:
      - main
      - feature/novo-titulo
  pull_request:
    branches:
      - main

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Executar testes
        run: node teste.js
